apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: jenkins
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.250-192.168.0.253

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
