podTemplate {
    node(jnlp-agent-docker) {
        stage('Run shell') {
            echo " ============== docker login =================="
                withCredentials([usernamePassword(credentialsId: 'kgorbarskij_dhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME -p $PASSWORD
                    """
                }
        }
    }
}
