podTemplate(containers: [
    containerTemplate(name: 'dind', image: 'jenkins/jnlp-agent-docker', command: '/bin/bash -c', args: 'cat'),
  ]) {
    deployment(POD_LABEL) {
        stage('docker login') {
                container('dind') {
                    stage('login'){
                        withCredentials([usernamePassword(credentialsId: 'kgorbarskij_dhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                            sh """
                            echo " ============== docker login =================="
                            docker login -u $USERNAME -p $PASSWORD

                            """
                        }
                    }

                }    
        }
    }
}
