apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 2048-autoscaling
  namespace: "2048"
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: "2048"
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60