apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048"
  namespace: "2048"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
        - name: "2048"
          image: kgorbarskij/2048:bf10553
          ports:
            - name: httpport
              containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: listener
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: 2048-data
              mountPath: /tmp
      volumes:
        - name: 2048-data
          persistentVolumeClaim:
            claimName: 2048-pv-claim
